import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#faf8ff',
        'surface-dim': '#d9d9e6',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f2ff',
        'surface-container': '#ededfa',
        'surface-container-high': '#e7e7f4',
        'surface-container-highest': '#e1e1ef',
        'on-surface': '#191b24',
        'on-surface-variant': '#494454',
        'inverse-surface': '#2e303a',
        'inverse-on-surface': '#f0f0fd',
        outline: '#7a7486',
        'outline-variant': '#cac3d7',
        'surface-tint': '#673fd6',
        primary: '#663ed5',
        'on-primary': '#ffffff',
        'primary-container': '#7f5af0',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#cdbdff',
        secondary: '#006783',
        'on-secondary': '#ffffff',
        'secondary-container': '#70d6ff',
        'on-secondary-container': '#005c75',
        tertiary: '#7540bc',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#8f5ad7',
        'on-tertiary-container': '#ffffff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e7deff',
        'primary-fixed-dim': '#cdbdff',
        'on-primary-fixed': '#20005f',
        'on-primary-fixed-variant': '#4e1dbe',
        'secondary-fixed': '#bce9ff',
        'secondary-fixed-dim': '#6cd3fc',
        'on-secondary-fixed': '#001f2a',
        'on-secondary-fixed-variant': '#004d63',
        'tertiary-fixed': '#eddcff',
        'tertiary-fixed-dim': '#d8baff',
        'on-tertiary-fixed': '#290055',
        'on-tertiary-fixed-variant': '#5d24a3',
        background: '#faf8ff',
        'on-background': '#191b24',
        'surface-variant': '#e1e1ef',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.5rem',
        'gutter-desktop': '2rem',
        margin: '1.5rem',
        'margin-desktop': '3rem',
        'space-xs': '0.375rem',
        'space-sm': '0.75rem',
        'space-md': '1.25rem',
        'space-lg': '2rem',
        'space-xl': '3rem',
      },
    },
  },
  plugins: [typography],
};
